cmake_minimum_required(VERSION 3.14)
project(redis)

set(CMAKE_CXX_STANDARD 14)

include_directories(deps/fast_float)
include_directories(deps/fpconv)
include_directories(deps/hdr_histogram)
include_directories(deps/hiredis)
include_directories(deps/hiredis/adapters)
include_directories(deps/hiredis/examples)
include_directories(deps/jemalloc/include)
include_directories(deps/jemalloc/include/jemalloc)
include_directories(deps/jemalloc/include/jemalloc/internal)
include_directories(deps/jemalloc/include/msvc_compat)
include_directories(deps/jemalloc/include/msvc_compat/C99)
include_directories(deps/jemalloc/msvc/test_threads)
include_directories(deps/jemalloc/test/include)
include_directories(deps/jemalloc/test/include/test)
include_directories(deps/jemalloc/test/unit)
include_directories(deps/linenoise)
include_directories(deps/lua/etc)
include_directories(deps/lua/src)
include_directories(src)

add_executable(redis
        deps/fast_float/fast_float.h
        deps/fast_float/fast_float_strtod.cpp
        deps/fast_float/fast_float_strtod.h
        deps/fpconv/fpconv_dtoa.c
        deps/fpconv/fpconv_dtoa.h
        deps/fpconv/fpconv_powers.h
        deps/hdr_histogram/hdr_atomic.h
        deps/hdr_histogram/hdr_histogram.c
        deps/hdr_histogram/hdr_histogram.h
        deps/hdr_histogram/hdr_redis_malloc.h
        deps/hdr_histogram/hdr_tests.h
        deps/hiredis/adapters/ae.h
        deps/hiredis/adapters/glib.h
        deps/hiredis/adapters/ivykis.h
        deps/hiredis/adapters/libev.h
        deps/hiredis/adapters/libevent.h
        deps/hiredis/adapters/libhv.h
        deps/hiredis/adapters/libsdevent.h
        deps/hiredis/adapters/libuv.h
        deps/hiredis/adapters/macosx.h
        deps/hiredis/adapters/poll.h
        deps/hiredis/adapters/qt.h
        deps/hiredis/adapters/redismoduleapi.h
        deps/hiredis/examples/example-ae.c
        deps/hiredis/examples/example-glib.c
        deps/hiredis/examples/example-ivykis.c
        deps/hiredis/examples/example-libev.c
        deps/hiredis/examples/example-libevent-ssl.c
        deps/hiredis/examples/example-libevent.c
        deps/hiredis/examples/example-libhv.c
        deps/hiredis/examples/example-libsdevent.c
        deps/hiredis/examples/example-libuv.c
        deps/hiredis/examples/example-macosx.c
        deps/hiredis/examples/example-poll.c
        deps/hiredis/examples/example-push.c
        deps/hiredis/examples/example-qt.cpp
        deps/hiredis/examples/example-qt.h
        deps/hiredis/examples/example-redismoduleapi.c
        deps/hiredis/examples/example-ssl.c
        deps/hiredis/examples/example.c
        deps/hiredis/fuzzing/format_command_fuzzer.c
        deps/hiredis/alloc.c
        deps/hiredis/alloc.h
        deps/hiredis/async.c
        deps/hiredis/async.h
        deps/hiredis/async_private.h
        deps/hiredis/dict.c
        deps/hiredis/dict.h
        deps/hiredis/fmacros.h
        deps/hiredis/hiredis.c
        deps/hiredis/hiredis.h
        deps/hiredis/hiredis_ssl.h
        deps/hiredis/net.c
        deps/hiredis/net.h
        deps/hiredis/read.c
        deps/hiredis/read.h
        deps/hiredis/sds.c
        deps/hiredis/sds.h
        deps/hiredis/sdsalloc.h
        deps/hiredis/sdscompat.h
        deps/hiredis/sockcompat.c
        deps/hiredis/sockcompat.h
        deps/hiredis/ssl.c
        deps/hiredis/test.c
        deps/hiredis/win32.h
        deps/jemalloc/include/jemalloc/internal/activity_callback.h
        deps/jemalloc/include/jemalloc/internal/arena_externs.h
        deps/jemalloc/include/jemalloc/internal/arena_inlines_a.h
        deps/jemalloc/include/jemalloc/internal/arena_inlines_b.h
        deps/jemalloc/include/jemalloc/internal/arena_stats.h
        deps/jemalloc/include/jemalloc/internal/arena_structs.h
        deps/jemalloc/include/jemalloc/internal/arena_types.h
        deps/jemalloc/include/jemalloc/internal/assert.h
        deps/jemalloc/include/jemalloc/internal/atomic.h
        deps/jemalloc/include/jemalloc/internal/atomic_c11.h
        deps/jemalloc/include/jemalloc/internal/atomic_gcc_atomic.h
        deps/jemalloc/include/jemalloc/internal/atomic_gcc_sync.h
        deps/jemalloc/include/jemalloc/internal/atomic_msvc.h
        deps/jemalloc/include/jemalloc/internal/background_thread_externs.h
        deps/jemalloc/include/jemalloc/internal/background_thread_inlines.h
        deps/jemalloc/include/jemalloc/internal/background_thread_structs.h
        deps/jemalloc/include/jemalloc/internal/base.h
        deps/jemalloc/include/jemalloc/internal/bin.h
        deps/jemalloc/include/jemalloc/internal/bin_info.h
        deps/jemalloc/include/jemalloc/internal/bin_stats.h
        deps/jemalloc/include/jemalloc/internal/bin_types.h
        deps/jemalloc/include/jemalloc/internal/bit_util.h
        deps/jemalloc/include/jemalloc/internal/bitmap.h
        deps/jemalloc/include/jemalloc/internal/buf_writer.h
        deps/jemalloc/include/jemalloc/internal/cache_bin.h
        deps/jemalloc/include/jemalloc/internal/ckh.h
        deps/jemalloc/include/jemalloc/internal/counter.h
        deps/jemalloc/include/jemalloc/internal/ctl.h
        deps/jemalloc/include/jemalloc/internal/decay.h
        deps/jemalloc/include/jemalloc/internal/div.h
        deps/jemalloc/include/jemalloc/internal/ecache.h
        deps/jemalloc/include/jemalloc/internal/edata.h
        deps/jemalloc/include/jemalloc/internal/edata_cache.h
        deps/jemalloc/include/jemalloc/internal/ehooks.h
        deps/jemalloc/include/jemalloc/internal/emap.h
        deps/jemalloc/include/jemalloc/internal/emitter.h
        deps/jemalloc/include/jemalloc/internal/eset.h
        deps/jemalloc/include/jemalloc/internal/exp_grow.h
        deps/jemalloc/include/jemalloc/internal/extent.h
        deps/jemalloc/include/jemalloc/internal/extent_dss.h
        deps/jemalloc/include/jemalloc/internal/extent_mmap.h
        deps/jemalloc/include/jemalloc/internal/fb.h
        deps/jemalloc/include/jemalloc/internal/fxp.h
        deps/jemalloc/include/jemalloc/internal/hash.h
        deps/jemalloc/include/jemalloc/internal/hook.h
        deps/jemalloc/include/jemalloc/internal/hpa.h
        deps/jemalloc/include/jemalloc/internal/hpa_hooks.h
        deps/jemalloc/include/jemalloc/internal/hpa_opts.h
        deps/jemalloc/include/jemalloc/internal/hpdata.h
        deps/jemalloc/include/jemalloc/internal/inspect.h
        deps/jemalloc/include/jemalloc/internal/jemalloc_internal_decls.h
        deps/jemalloc/include/jemalloc/internal/jemalloc_internal_externs.h
        deps/jemalloc/include/jemalloc/internal/jemalloc_internal_includes.h
        deps/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_a.h
        deps/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_b.h
        deps/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h
        deps/jemalloc/include/jemalloc/internal/jemalloc_internal_macros.h
        deps/jemalloc/include/jemalloc/internal/jemalloc_internal_types.h
        deps/jemalloc/include/jemalloc/internal/large_externs.h
        deps/jemalloc/include/jemalloc/internal/lockedint.h
        deps/jemalloc/include/jemalloc/internal/log.h
        deps/jemalloc/include/jemalloc/internal/malloc_io.h
        deps/jemalloc/include/jemalloc/internal/mpsc_queue.h
        deps/jemalloc/include/jemalloc/internal/mutex.h
        deps/jemalloc/include/jemalloc/internal/mutex_prof.h
        deps/jemalloc/include/jemalloc/internal/nstime.h
        deps/jemalloc/include/jemalloc/internal/pa.h
        deps/jemalloc/include/jemalloc/internal/pac.h
        deps/jemalloc/include/jemalloc/internal/pages.h
        deps/jemalloc/include/jemalloc/internal/pai.h
        deps/jemalloc/include/jemalloc/internal/peak.h
        deps/jemalloc/include/jemalloc/internal/peak_event.h
        deps/jemalloc/include/jemalloc/internal/ph.h
        deps/jemalloc/include/jemalloc/internal/prng.h
        deps/jemalloc/include/jemalloc/internal/prof_data.h
        deps/jemalloc/include/jemalloc/internal/prof_externs.h
        deps/jemalloc/include/jemalloc/internal/prof_hook.h
        deps/jemalloc/include/jemalloc/internal/prof_inlines.h
        deps/jemalloc/include/jemalloc/internal/prof_log.h
        deps/jemalloc/include/jemalloc/internal/prof_recent.h
        deps/jemalloc/include/jemalloc/internal/prof_stats.h
        deps/jemalloc/include/jemalloc/internal/prof_structs.h
        deps/jemalloc/include/jemalloc/internal/prof_sys.h
        deps/jemalloc/include/jemalloc/internal/prof_types.h
        deps/jemalloc/include/jemalloc/internal/psset.h
        deps/jemalloc/include/jemalloc/internal/ql.h
        deps/jemalloc/include/jemalloc/internal/qr.h
        deps/jemalloc/include/jemalloc/internal/quantum.h
        deps/jemalloc/include/jemalloc/internal/rb.h
        deps/jemalloc/include/jemalloc/internal/rtree.h
        deps/jemalloc/include/jemalloc/internal/rtree_tsd.h
        deps/jemalloc/include/jemalloc/internal/safety_check.h
        deps/jemalloc/include/jemalloc/internal/san.h
        deps/jemalloc/include/jemalloc/internal/san_bump.h
        deps/jemalloc/include/jemalloc/internal/sc.h
        deps/jemalloc/include/jemalloc/internal/sec.h
        deps/jemalloc/include/jemalloc/internal/sec_opts.h
        deps/jemalloc/include/jemalloc/internal/seq.h
        deps/jemalloc/include/jemalloc/internal/slab_data.h
        deps/jemalloc/include/jemalloc/internal/smoothstep.h
        deps/jemalloc/include/jemalloc/internal/spin.h
        deps/jemalloc/include/jemalloc/internal/stats.h
        deps/jemalloc/include/jemalloc/internal/sz.h
        deps/jemalloc/include/jemalloc/internal/tcache_externs.h
        deps/jemalloc/include/jemalloc/internal/tcache_inlines.h
        deps/jemalloc/include/jemalloc/internal/tcache_structs.h
        deps/jemalloc/include/jemalloc/internal/tcache_types.h
        deps/jemalloc/include/jemalloc/internal/test_hooks.h
        deps/jemalloc/include/jemalloc/internal/thread_event.h
        deps/jemalloc/include/jemalloc/internal/ticker.h
        deps/jemalloc/include/jemalloc/internal/tsd.h
        deps/jemalloc/include/jemalloc/internal/tsd_generic.h
        deps/jemalloc/include/jemalloc/internal/tsd_malloc_thread_cleanup.h
        deps/jemalloc/include/jemalloc/internal/tsd_tls.h
        deps/jemalloc/include/jemalloc/internal/tsd_types.h
        deps/jemalloc/include/jemalloc/internal/tsd_win.h
        deps/jemalloc/include/jemalloc/internal/typed_list.h
        deps/jemalloc/include/jemalloc/internal/util.h
        deps/jemalloc/include/jemalloc/internal/witness.h
        deps/jemalloc/include/msvc_compat/C99/stdbool.h
        deps/jemalloc/include/msvc_compat/C99/stdint.h
        deps/jemalloc/include/msvc_compat/strings.h
        deps/jemalloc/include/msvc_compat/windows_extra.h
        deps/jemalloc/msvc/test_threads/test_threads.cpp
        deps/jemalloc/msvc/test_threads/test_threads.h
        deps/jemalloc/msvc/test_threads/test_threads_main.cpp
        deps/jemalloc/src/arena.c
        deps/jemalloc/src/background_thread.c
        deps/jemalloc/src/base.c
        deps/jemalloc/src/bin.c
        deps/jemalloc/src/bin_info.c
        deps/jemalloc/src/bitmap.c
        deps/jemalloc/src/buf_writer.c
        deps/jemalloc/src/cache_bin.c
        deps/jemalloc/src/ckh.c
        deps/jemalloc/src/counter.c
        deps/jemalloc/src/ctl.c
        deps/jemalloc/src/decay.c
        deps/jemalloc/src/div.c
        deps/jemalloc/src/ecache.c
        deps/jemalloc/src/edata.c
        deps/jemalloc/src/edata_cache.c
        deps/jemalloc/src/ehooks.c
        deps/jemalloc/src/emap.c
        deps/jemalloc/src/eset.c
        deps/jemalloc/src/exp_grow.c
        deps/jemalloc/src/extent.c
        deps/jemalloc/src/extent_dss.c
        deps/jemalloc/src/extent_mmap.c
        deps/jemalloc/src/fxp.c
        deps/jemalloc/src/hook.c
        deps/jemalloc/src/hpa.c
        deps/jemalloc/src/hpa_hooks.c
        deps/jemalloc/src/hpdata.c
        deps/jemalloc/src/inspect.c
        deps/jemalloc/src/jemalloc.c
        deps/jemalloc/src/jemalloc_cpp.cpp
        deps/jemalloc/src/large.c
        deps/jemalloc/src/log.c
        deps/jemalloc/src/malloc_io.c
        deps/jemalloc/src/mutex.c
        deps/jemalloc/src/nstime.c
        deps/jemalloc/src/pa.c
        deps/jemalloc/src/pa_extra.c
        deps/jemalloc/src/pac.c
        deps/jemalloc/src/pages.c
        deps/jemalloc/src/pai.c
        deps/jemalloc/src/peak_event.c
        deps/jemalloc/src/prof.c
        deps/jemalloc/src/prof_data.c
        deps/jemalloc/src/prof_log.c
        deps/jemalloc/src/prof_recent.c
        deps/jemalloc/src/prof_stats.c
        deps/jemalloc/src/prof_sys.c
        deps/jemalloc/src/psset.c
        deps/jemalloc/src/rtree.c
        deps/jemalloc/src/safety_check.c
        deps/jemalloc/src/san.c
        deps/jemalloc/src/san_bump.c
        deps/jemalloc/src/sc.c
        deps/jemalloc/src/sec.c
        deps/jemalloc/src/stats.c
        deps/jemalloc/src/sz.c
        deps/jemalloc/src/tcache.c
        deps/jemalloc/src/test_hooks.c
        deps/jemalloc/src/thread_event.c
        deps/jemalloc/src/ticker.c
        deps/jemalloc/src/tsd.c
        deps/jemalloc/src/witness.c
        deps/jemalloc/src/zone.c
        deps/jemalloc/test/analyze/prof_bias.c
        deps/jemalloc/test/analyze/rand.c
        deps/jemalloc/test/analyze/sizes.c
        deps/jemalloc/test/include/test/arena_util.h
        deps/jemalloc/test/include/test/bench.h
        deps/jemalloc/test/include/test/bgthd.h
        deps/jemalloc/test/include/test/btalloc.h
        deps/jemalloc/test/include/test/extent_hooks.h
        deps/jemalloc/test/include/test/math.h
        deps/jemalloc/test/include/test/mq.h
        deps/jemalloc/test/include/test/mtx.h
        deps/jemalloc/test/include/test/nbits.h
        deps/jemalloc/test/include/test/san.h
        deps/jemalloc/test/include/test/SFMT-alti.h
        deps/jemalloc/test/include/test/SFMT-params.h
        deps/jemalloc/test/include/test/SFMT-params11213.h
        deps/jemalloc/test/include/test/SFMT-params1279.h
        deps/jemalloc/test/include/test/SFMT-params132049.h
        deps/jemalloc/test/include/test/SFMT-params19937.h
        deps/jemalloc/test/include/test/SFMT-params216091.h
        deps/jemalloc/test/include/test/SFMT-params2281.h
        deps/jemalloc/test/include/test/SFMT-params4253.h
        deps/jemalloc/test/include/test/SFMT-params44497.h
        deps/jemalloc/test/include/test/SFMT-params607.h
        deps/jemalloc/test/include/test/SFMT-params86243.h
        deps/jemalloc/test/include/test/SFMT-sse2.h
        deps/jemalloc/test/include/test/SFMT.h
        deps/jemalloc/test/include/test/sleep.h
        deps/jemalloc/test/include/test/test.h
        deps/jemalloc/test/include/test/thd.h
        deps/jemalloc/test/include/test/timer.h
        deps/jemalloc/test/integration/cpp/basic.cpp
        deps/jemalloc/test/integration/cpp/infallible_new_false.cpp
        deps/jemalloc/test/integration/cpp/infallible_new_true.cpp
        deps/jemalloc/test/integration/aligned_alloc.c
        deps/jemalloc/test/integration/allocated.c
        deps/jemalloc/test/integration/extent.c
        deps/jemalloc/test/integration/malloc.c
        deps/jemalloc/test/integration/mallocx.c
        deps/jemalloc/test/integration/MALLOCX_ARENA.c
        deps/jemalloc/test/integration/overflow.c
        deps/jemalloc/test/integration/posix_memalign.c
        deps/jemalloc/test/integration/rallocx.c
        deps/jemalloc/test/integration/sdallocx.c
        deps/jemalloc/test/integration/slab_sizes.c
        deps/jemalloc/test/integration/smallocx.c
        deps/jemalloc/test/integration/thread_arena.c
        deps/jemalloc/test/integration/thread_tcache_enabled.c
        deps/jemalloc/test/integration/xallocx.c
        deps/jemalloc/test/src/btalloc.c
        deps/jemalloc/test/src/btalloc_0.c
        deps/jemalloc/test/src/btalloc_1.c
        deps/jemalloc/test/src/math.c
        deps/jemalloc/test/src/mtx.c
        deps/jemalloc/test/src/SFMT.c
        deps/jemalloc/test/src/sleep.c
        deps/jemalloc/test/src/test.c
        deps/jemalloc/test/src/thd.c
        deps/jemalloc/test/src/timer.c
        deps/jemalloc/test/stress/batch_alloc.c
        deps/jemalloc/test/stress/fill_flush.c
        deps/jemalloc/test/stress/hookbench.c
        deps/jemalloc/test/stress/large_microbench.c
        deps/jemalloc/test/stress/mallctl.c
        deps/jemalloc/test/stress/microbench.c
        deps/jemalloc/test/unit/a0.c
        deps/jemalloc/test/unit/arena_decay.c
        deps/jemalloc/test/unit/arena_reset.c
        deps/jemalloc/test/unit/arena_reset_prof.c
        deps/jemalloc/test/unit/atomic.c
        deps/jemalloc/test/unit/background_thread.c
        deps/jemalloc/test/unit/background_thread_enable.c
        deps/jemalloc/test/unit/base.c
        deps/jemalloc/test/unit/batch_alloc.c
        deps/jemalloc/test/unit/batch_alloc_prof.c
        deps/jemalloc/test/unit/binshard.c
        deps/jemalloc/test/unit/bit_util.c
        deps/jemalloc/test/unit/bitmap.c
        deps/jemalloc/test/unit/buf_writer.c
        deps/jemalloc/test/unit/cache_bin.c
        deps/jemalloc/test/unit/ckh.c
        deps/jemalloc/test/unit/counter.c
        deps/jemalloc/test/unit/decay.c
        deps/jemalloc/test/unit/div.c
        deps/jemalloc/test/unit/double_free.c
        deps/jemalloc/test/unit/double_free.h
        deps/jemalloc/test/unit/edata_cache.c
        deps/jemalloc/test/unit/emitter.c
        deps/jemalloc/test/unit/extent_quantize.c
        deps/jemalloc/test/unit/fb.c
        deps/jemalloc/test/unit/fork.c
        deps/jemalloc/test/unit/fxp.c
        deps/jemalloc/test/unit/hash.c
        deps/jemalloc/test/unit/hook.c
        deps/jemalloc/test/unit/hpa.c
        deps/jemalloc/test/unit/hpa_background_thread.c
        deps/jemalloc/test/unit/hpdata.c
        deps/jemalloc/test/unit/huge.c
        deps/jemalloc/test/unit/inspect.c
        deps/jemalloc/test/unit/junk.c
        deps/jemalloc/test/unit/junk_alloc.c
        deps/jemalloc/test/unit/junk_free.c
        deps/jemalloc/test/unit/log.c
        deps/jemalloc/test/unit/mallctl.c
        deps/jemalloc/test/unit/malloc_conf_2.c
        deps/jemalloc/test/unit/malloc_io.c
        deps/jemalloc/test/unit/math.c
        deps/jemalloc/test/unit/mpsc_queue.c
        deps/jemalloc/test/unit/mq.c
        deps/jemalloc/test/unit/mtx.c
        deps/jemalloc/test/unit/nstime.c
        deps/jemalloc/test/unit/oversize_threshold.c
        deps/jemalloc/test/unit/pa.c
        deps/jemalloc/test/unit/pack.c
        deps/jemalloc/test/unit/pages.c
        deps/jemalloc/test/unit/peak.c
        deps/jemalloc/test/unit/ph.c
        deps/jemalloc/test/unit/prng.c
        deps/jemalloc/test/unit/prof_accum.c
        deps/jemalloc/test/unit/prof_active.c
        deps/jemalloc/test/unit/prof_gdump.c
        deps/jemalloc/test/unit/prof_hook.c
        deps/jemalloc/test/unit/prof_idump.c
        deps/jemalloc/test/unit/prof_log.c
        deps/jemalloc/test/unit/prof_mdump.c
        deps/jemalloc/test/unit/prof_recent.c
        deps/jemalloc/test/unit/prof_reset.c
        deps/jemalloc/test/unit/prof_stats.c
        deps/jemalloc/test/unit/prof_sys_thread_name.c
        deps/jemalloc/test/unit/prof_tctx.c
        deps/jemalloc/test/unit/prof_thread_name.c
        deps/jemalloc/test/unit/psset.c
        deps/jemalloc/test/unit/ql.c
        deps/jemalloc/test/unit/qr.c
        deps/jemalloc/test/unit/rb.c
        deps/jemalloc/test/unit/retained.c
        deps/jemalloc/test/unit/rtree.c
        deps/jemalloc/test/unit/safety_check.c
        deps/jemalloc/test/unit/san.c
        deps/jemalloc/test/unit/san_bump.c
        deps/jemalloc/test/unit/sc.c
        deps/jemalloc/test/unit/sec.c
        deps/jemalloc/test/unit/seq.c
        deps/jemalloc/test/unit/SFMT.c
        deps/jemalloc/test/unit/size_check.c
        deps/jemalloc/test/unit/size_classes.c
        deps/jemalloc/test/unit/slab.c
        deps/jemalloc/test/unit/smoothstep.c
        deps/jemalloc/test/unit/spin.c
        deps/jemalloc/test/unit/stats.c
        deps/jemalloc/test/unit/stats_print.c
        deps/jemalloc/test/unit/sz.c
        deps/jemalloc/test/unit/tcache_max.c
        deps/jemalloc/test/unit/test_hooks.c
        deps/jemalloc/test/unit/thread_event.c
        deps/jemalloc/test/unit/ticker.c
        deps/jemalloc/test/unit/tsd.c
        deps/jemalloc/test/unit/uaf.c
        deps/jemalloc/test/unit/witness.c
        deps/jemalloc/test/unit/zero.c
        deps/jemalloc/test/unit/zero_realloc_abort.c
        deps/jemalloc/test/unit/zero_realloc_alloc.c
        deps/jemalloc/test/unit/zero_realloc_free.c
        deps/jemalloc/test/unit/zero_reallocs.c
        deps/linenoise/example.c
        deps/linenoise/linenoise.c
        deps/linenoise/linenoise.h
        deps/lua/etc/all.c
        deps/lua/etc/lua.hpp
        deps/lua/etc/min.c
        deps/lua/etc/noparser.c
        deps/lua/src/fpconv.c
        deps/lua/src/fpconv.h
        deps/lua/src/lapi.c
        deps/lua/src/lapi.h
        deps/lua/src/lauxlib.c
        deps/lua/src/lauxlib.h
        deps/lua/src/lbaselib.c
        deps/lua/src/lcode.c
        deps/lua/src/lcode.h
        deps/lua/src/ldblib.c
        deps/lua/src/ldebug.c
        deps/lua/src/ldebug.h
        deps/lua/src/ldo.c
        deps/lua/src/ldo.h
        deps/lua/src/ldump.c
        deps/lua/src/lfunc.c
        deps/lua/src/lfunc.h
        deps/lua/src/lgc.c
        deps/lua/src/lgc.h
        deps/lua/src/linit.c
        deps/lua/src/liolib.c
        deps/lua/src/llex.c
        deps/lua/src/llex.h
        deps/lua/src/llimits.h
        deps/lua/src/lmathlib.c
        deps/lua/src/lmem.c
        deps/lua/src/lmem.h
        deps/lua/src/loadlib.c
        deps/lua/src/lobject.c
        deps/lua/src/lobject.h
        deps/lua/src/lopcodes.c
        deps/lua/src/lopcodes.h
        deps/lua/src/loslib.c
        deps/lua/src/lparser.c
        deps/lua/src/lparser.h
        deps/lua/src/lstate.c
        deps/lua/src/lstate.h
        deps/lua/src/lstring.c
        deps/lua/src/lstring.h
        deps/lua/src/lstrlib.c
        deps/lua/src/ltable.c
        deps/lua/src/ltable.h
        deps/lua/src/ltablib.c
        deps/lua/src/ltm.c
        deps/lua/src/ltm.h
        deps/lua/src/lua.c
        deps/lua/src/lua.h
        deps/lua/src/lua_bit.c
        deps/lua/src/lua_cjson.c
        deps/lua/src/lua_cmsgpack.c
        deps/lua/src/lua_struct.c
        deps/lua/src/luac.c
        deps/lua/src/luaconf.h
        deps/lua/src/lualib.h
        deps/lua/src/lundump.c
        deps/lua/src/lundump.h
        deps/lua/src/lvm.c
        deps/lua/src/lvm.h
        deps/lua/src/lzio.c
        deps/lua/src/lzio.h
        deps/lua/src/print.c
        deps/lua/src/strbuf.c
        deps/lua/src/strbuf.h
        src/modules/helloacl.c
        src/modules/helloblock.c
        src/modules/hellocluster.c
        src/modules/hellodict.c
        src/modules/hellohook.c
        src/modules/hellotimer.c
        src/modules/hellotype.c
        src/modules/helloworld.c
        src/acl.c
        src/adlist.c
        src/adlist.h
        src/ae.c
        src/ae.h
        src/ae_epoll.c
        src/ae_evport.c
        src/ae_kqueue.c
        src/ae_select.c
        src/anet.c
        src/anet.h
        src/aof.c
        src/asciilogo.h
        src/atomicvar.h
        src/bio.c
        src/bio.h
        src/bitops.c
        src/blocked.c
        src/call_reply.c
        src/call_reply.h
        src/childinfo.c
        src/cli_commands.c
        src/cli_commands.h
        src/cli_common.c
        src/cli_common.h
        src/cluster.c
        src/cluster.h
        src/cluster_legacy.c
        src/cluster_legacy.h
        src/commands.c
        src/commands.h
        src/config.c
        src/config.h
        src/connection.c
        src/connection.h
        src/connhelpers.h
        src/crc16.c
        src/crc16_slottable.h
        src/crc64.c
        src/crc64.h
        src/crccombine.c
        src/crccombine.h
        src/crcspeed.c
        src/crcspeed.h
        src/db.c
        src/debug.c
        src/debugmacro.h
        src/defrag.c
        src/dict.c
        src/dict.h
        src/ebuckets.c
        src/ebuckets.h
        src/endianconv.c
        src/endianconv.h
        src/eval.c
        src/eventnotifier.c
        src/eventnotifier.h
        src/evict.c
        src/expire.c
        src/fmacros.h
        src/fmtargs.h
        src/function_lua.c
        src/functions.c
        src/functions.h
        src/geo.c
        src/geo.h
        src/geohash.c
        src/geohash.h
        src/geohash_helper.c
        src/geohash_helper.h
        src/hyperloglog.c
        src/intset.c
        src/intset.h
        src/iothread.c
        src/kvstore.c
        src/kvstore.h
        src/latency.c
        src/latency.h
        src/lazyfree.c
        src/listpack.c
        src/listpack.h
        src/listpack_malloc.h
        src/localtime.c
        src/logreqres.c
        src/lolwut.c
        src/lolwut.h
        src/lolwut5.c
        src/lolwut6.c
        src/lzf.h
        src/lzf_c.c
        src/lzf_d.c
        src/lzfP.h
        src/memtest.c
        src/module.c
        src/monotonic.c
        src/monotonic.h
        src/mstr.c
        src/mstr.h
        src/mt19937-64.c
        src/mt19937-64.h
        src/multi.c
        src/networking.c
        src/notify.c
        src/object.c
        src/pqsort.c
        src/pqsort.h
        src/pubsub.c
        src/quicklist.c
        src/quicklist.h
        src/rand.c
        src/rand.h
        src/rax.c
        src/rax.h
        src/rax_malloc.h
        src/rdb.c
        src/rdb.h
        src/redis-benchmark.c
        src/redis-check-aof.c
        src/redis-check-rdb.c
        src/redis-cli.c
        src/redisassert.c
        src/redisassert.h
        src/redismodule.h
        src/release.c
        src/replication.c
        src/resp_parser.c
        src/resp_parser.h
        src/rio.c
        src/rio.h
        src/script.c
        src/script.h
        src/script_lua.c
        src/script_lua.h
        src/sds.c
        src/sds.h
        src/sdsalloc.h
        src/sentinel.c
        src/server.c
        src/server.h
        src/setcpuaffinity.c
        src/setproctitle.c
        src/sha1.c
        src/sha1.h
        src/sha256.c
        src/sha256.h
        src/siphash.c
        src/slowlog.c
        src/slowlog.h
        src/socket.c
        src/solarisfixes.h
        src/sort.c
        src/sparkline.c
        src/sparkline.h
        src/stream.h
        src/strl.c
        src/syncio.c
        src/syscheck.c
        src/syscheck.h
        src/t_hash.c
        src/t_list.c
        src/t_set.c
        src/t_stream.c
        src/t_string.c
        src/t_zset.c
        src/testhelp.h
        src/threads_mngr.c
        src/threads_mngr.h
        src/timeout.c
        src/tls.c
        src/tracking.c
        src/unix.c
        src/util.c
        src/util.h
        src/version.h
        src/ziplist.c
        src/ziplist.h
        src/zipmap.c
        src/zipmap.h
        src/zmalloc.c
        src/zmalloc.h
        tests/modules/aclcheck.c
        tests/modules/auth.c
        tests/modules/basics.c
        tests/modules/blockedclient.c
        tests/modules/blockonbackground.c
        tests/modules/blockonkeys.c
        tests/modules/cmdintrospection.c
        tests/modules/commandfilter.c
        tests/modules/crash.c
        tests/modules/datatype.c
        tests/modules/datatype2.c
        tests/modules/defragtest.c
        tests/modules/eventloop.c
        tests/modules/fork.c
        tests/modules/getchannels.c
        tests/modules/getkeys.c
        tests/modules/hash.c
        tests/modules/hooks.c
        tests/modules/infotest.c
        tests/modules/internalsecret.c
        tests/modules/keyspace_events.c
        tests/modules/keyspecs.c
        tests/modules/list.c
        tests/modules/mallocsize.c
        tests/modules/misc.c
        tests/modules/moduleauthtwo.c
        tests/modules/moduleconfigs.c
        tests/modules/moduleconfigstwo.c
        tests/modules/postnotifications.c
        tests/modules/propagate.c
        tests/modules/publish.c
        tests/modules/rdbloadsave.c
        tests/modules/reply.c
        tests/modules/scan.c
        tests/modules/stream.c
        tests/modules/subcommands.c
        tests/modules/test_lazyfree.c
        tests/modules/testrdb.c
        tests/modules/timer.c
        tests/modules/usercall.c
        tests/modules/zset.c
        utils/lru/lfu-simulation.c
        utils/corrupt_rdb.c
        utils/tracking_collisions.c)
